// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Umbraco.Cms.Persistence.EFCore;

#nullable disable

namespace Umbraco.Cms.Persistence.EFCore.PostgreSQL.Migrations
{
    [DbContext(typeof(UmbracoDbContext))]
    [Migration("20260725140419_AddUserLoginAndClientIds")]
    partial class AddUserLoginAndClientIds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("application_type");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("text")
                        .HasColumnName("client_secret");

                    b.Property<string>("ClientType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("client_type");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("concurrency_token");

                    b.Property<string>("ConsentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("consent_type");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text")
                        .HasColumnName("display_names");

                    b.Property<string>("JsonWebKeySet")
                        .HasColumnType("text")
                        .HasColumnName("json_web_key_set");

                    b.Property<string>("Permissions")
                        .HasColumnType("text")
                        .HasColumnName("permissions");

                    b.Property<string>("PostLogoutRedirectUris")
                        .HasColumnType("text")
                        .HasColumnName("post_logout_redirect_uris");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<string>("RedirectUris")
                        .HasColumnType("text")
                        .HasColumnName("redirect_uris");

                    b.Property<string>("Requirements")
                        .HasColumnType("text")
                        .HasColumnName("requirements");

                    b.Property<string>("Settings")
                        .HasColumnType("text")
                        .HasColumnName("settings");

                    b.HasKey("Id")
                        .HasName("pk_umbraco_open_iddict_applications");

                    b.HasIndex("ClientId")
                        .IsUnique()
                        .HasDatabaseName("ix_umbraco_open_iddict_applications_client_id");

                    b.ToTable("umbraco_open_iddict_applications", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text")
                        .HasColumnName("application_id");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<string>("Scopes")
                        .HasColumnType("text")
                        .HasColumnName("scopes");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("subject");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_umbraco_open_iddict_authorizations");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type")
                        .HasDatabaseName("ix_umbraco_open_iddict_authorizations_application_id_status_su~");

                    b.ToTable("umbraco_open_iddict_authorizations", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreScope", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("concurrency_token");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Descriptions")
                        .HasColumnType("text")
                        .HasColumnName("descriptions");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text")
                        .HasColumnName("display_names");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<string>("Resources")
                        .HasColumnType("text")
                        .HasColumnName("resources");

                    b.HasKey("Id")
                        .HasName("pk_umbraco_open_iddict_scopes");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_umbraco_open_iddict_scopes_name");

                    b.ToTable("umbraco_open_iddict_scopes", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text")
                        .HasColumnName("application_id");

                    b.Property<string>("AuthorizationId")
                        .HasColumnType("text")
                        .HasColumnName("authorization_id");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date");

                    b.Property<string>("Payload")
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<DateTime?>("RedemptionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redemption_date");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_id");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("subject");

                    b.Property<string>("Type")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_umbraco_open_iddict_tokens");

                    b.HasIndex("AuthorizationId")
                        .HasDatabaseName("ix_umbraco_open_iddict_tokens_authorization_id");

                    b.HasIndex("ReferenceId")
                        .IsUnique()
                        .HasDatabaseName("ix_umbraco_open_iddict_tokens_reference_id");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type")
                        .HasDatabaseName("ix_umbraco_open_iddict_tokens_application_id_status_subject_ty~");

                    b.ToTable("umbraco_open_iddict_tokens", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.User2ClientIdDto", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("ClientId")
                        .HasColumnType("text")
                        .HasColumnName("client_id");

                    b.HasKey("UserId", "ClientId")
                        .HasName("pk_umbraco_user2_client_id");

                    b.ToTable("umbraco_user2_client_id", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.UserDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("text")
                        .HasColumnName("avatar");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("user_disabled");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_email");

                    b.Property<DateTime?>("EmailConfirmedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_confirmed_date");

                    b.Property<int?>("FailedLoginAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_attempts");

                    b.Property<DateTime?>("InvitedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invited_date");

                    b.Property<Guid>("Key")
                        .HasColumnType("uuid")
                        .HasColumnName("key");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<DateTime?>("LastLockoutDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_lockout_date");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_date");

                    b.Property<DateTime?>("LastPasswordChangeDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_password_change_date");

                    b.Property<string>("Login")
                        .HasColumnType("text")
                        .HasColumnName("user_login");

                    b.Property<bool>("NoConsole")
                        .HasColumnType("boolean")
                        .HasColumnName("user_no_console");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("user_password");

                    b.Property<string>("PasswordConfig")
                        .HasColumnType("text")
                        .HasColumnName("password_config");

                    b.Property<string>("SecurityStampToken")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp_token");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<string>("UserLanguage")
                        .HasColumnType("text")
                        .HasColumnName("user_language");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_umbraco_user");

                    b.ToTable("umbraco_user", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.UserGroup2AppDto", b =>
                {
                    b.Property<int>("UserGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("user_group_id");

                    b.Property<string>("AppAlias")
                        .HasColumnType("text")
                        .HasColumnName("app");

                    b.HasKey("UserGroupId", "AppAlias")
                        .HasName("pk_umbraco_user_group2_app");

                    b.ToTable("umbraco_user_group2_app", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.UserGroup2GranularPermissionDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("context");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("permission");

                    b.Property<Guid?>("UniqueId")
                        .HasColumnType("uuid")
                        .HasColumnName("unique_id");

                    b.Property<Guid>("UserGroupKey")
                        .HasColumnType("uuid")
                        .HasColumnName("user_group_key");

                    b.HasKey("Id")
                        .HasName("pk_umbraco_user_group2_granular_permission");

                    b.HasIndex("UserGroupKey")
                        .HasDatabaseName("ix_umbraco_user_group2_granular_permission_user_group_key");

                    b.ToTable("umbraco_user_group2_granular_permission", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.UserGroup2LanguageDto", b =>
                {
                    b.Property<int>("UserGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("user_group_id");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer")
                        .HasColumnName("language_id");

                    b.HasKey("UserGroupId", "LanguageId")
                        .HasName("pk_umbraco_user_group2_language");

                    b.ToTable("umbraco_user_group2_language", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.UserGroup2PermissionDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("permission");

                    b.Property<Guid>("UserGroupKey")
                        .HasColumnType("uuid")
                        .HasColumnName("user_group_key");

                    b.HasKey("Id")
                        .HasName("pk_umbraco_user_group2_permission");

                    b.HasIndex("UserGroupKey")
                        .HasDatabaseName("ix_umbraco_user_group2_permission_user_group_key");

                    b.ToTable("umbraco_user_group2_permission", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.UserGroupDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasColumnType("text")
                        .HasColumnName("user_group_alias");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("DefaultPermissions")
                        .HasColumnType("text")
                        .HasColumnName("user_group_default_permissions");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("HasAccessToAllLanguages")
                        .HasColumnType("boolean")
                        .HasColumnName("has_access_to_all_languages");

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<Guid>("Key")
                        .HasColumnType("uuid")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("user_group_name");

                    b.Property<int?>("StartContentId")
                        .HasColumnType("integer")
                        .HasColumnName("start_content_id");

                    b.Property<int?>("StartElementId")
                        .HasColumnType("integer")
                        .HasColumnName("start_element_id");

                    b.Property<int?>("StartMediaId")
                        .HasColumnType("integer")
                        .HasColumnName("start_media_id");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.HasKey("Id")
                        .HasName("pk_umbraco_user_group");

                    b.HasAlternateKey("Key")
                        .HasName("ak_umbraco_user_group_key");

                    b.ToTable("umbraco_user_group", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.UserLoginDto", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("LastValidated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_validated_utc");

                    b.Property<DateTime>("LoggedIn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_in_utc");

                    b.Property<DateTime?>("LoggedOut")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_out_utc");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("SessionId")
                        .HasName("pk_umbraco_user_login");

                    b.ToTable("umbraco_user_login", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.UserStartNodeDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("StartNode")
                        .HasColumnType("integer")
                        .HasColumnName("start_node");

                    b.Property<int>("StartNodeType")
                        .HasColumnType("integer")
                        .HasColumnName("start_node_type");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_umbraco_user_start_node");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_umbraco_user_start_node_user_id");

                    b.ToTable("umbraco_user_start_node", (string)null);
                });

            modelBuilder.Entity("umbracoUser2UserGroup", b =>
                {
                    b.Property<int>("userGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("user_group_id");

                    b.Property<int>("userId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("userGroupId", "userId")
                        .HasName("pk_umbraco_user2_user_group");

                    b.HasIndex("userId")
                        .HasDatabaseName("ix_umbraco_user2_user_group_user_id");

                    b.ToTable("umbraco_user2_user_group");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Authorizations")
                        .HasForeignKey("ApplicationId")
                        .HasConstraintName("fk_umbraco_open_iddict_authorizations_umbraco_open_iddict_appl~");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Tokens")
                        .HasForeignKey("ApplicationId")
                        .HasConstraintName("fk_umbraco_open_iddict_tokens_umbraco_open_iddict_applications~");

                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", "Authorization")
                        .WithMany("Tokens")
                        .HasForeignKey("AuthorizationId")
                        .HasConstraintName("fk_umbraco_open_iddict_tokens_umbraco_open_iddict_authorizatio~");

                    b.Navigation("Application");

                    b.Navigation("Authorization");
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.UserGroup2AppDto", b =>
                {
                    b.HasOne("Umbraco.Cms.Infrastructure.Persistence.Dtos.UserGroupDto", null)
                        .WithMany("UserGroup2AppDtos")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_umbraco_user_group2_app_umbraco_user_group_user_group_id");
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.UserGroup2GranularPermissionDto", b =>
                {
                    b.HasOne("Umbraco.Cms.Infrastructure.Persistence.Dtos.UserGroupDto", null)
                        .WithMany("UserGroup2GranularPermissionDtos")
                        .HasForeignKey("UserGroupKey")
                        .HasPrincipalKey("Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_umbraco_user_group2_granular_permission_umbraco_user_group_us~");
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.UserGroup2LanguageDto", b =>
                {
                    b.HasOne("Umbraco.Cms.Infrastructure.Persistence.Dtos.UserGroupDto", null)
                        .WithMany("UserGroup2LanguageDtos")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_umbraco_user_group2_language_umbraco_user_group_user_group_id");
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.UserGroup2PermissionDto", b =>
                {
                    b.HasOne("Umbraco.Cms.Infrastructure.Persistence.Dtos.UserGroupDto", null)
                        .WithMany("UserGroup2PermissionDtos")
                        .HasForeignKey("UserGroupKey")
                        .HasPrincipalKey("Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_umbraco_user_group2_permission_umbraco_user_group_user_group_~");
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.UserStartNodeDto", b =>
                {
                    b.HasOne("Umbraco.Cms.Infrastructure.Persistence.Dtos.UserDto", null)
                        .WithMany("UserStartNodeDtos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_umbraco_user_start_node_umbraco_user_user_id");
                });

            modelBuilder.Entity("umbracoUser2UserGroup", b =>
                {
                    b.HasOne("Umbraco.Cms.Infrastructure.Persistence.Dtos.UserGroupDto", null)
                        .WithMany()
                        .HasForeignKey("userGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_umbraco_user2_user_group_umbraco_user_group_user_group_id");

                    b.HasOne("Umbraco.Cms.Infrastructure.Persistence.Dtos.UserDto", null)
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_umbraco_user2_user_group_umbraco_user_user_id");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Navigation("Authorizations");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.UserDto", b =>
                {
                    b.Navigation("UserStartNodeDtos");
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.UserGroupDto", b =>
                {
                    b.Navigation("UserGroup2AppDtos");

                    b.Navigation("UserGroup2GranularPermissionDtos");

                    b.Navigation("UserGroup2LanguageDtos");

                    b.Navigation("UserGroup2PermissionDtos");
                });
#pragma warning restore 612, 618
        }
    }
}
